"""empty message

Revision ID: 38c7b2c51a61
Revises: 
Create Date: 2022-04-22 00:22:56.334006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c7b2c51a61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_weibo',
    sa.Column('mid', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('from_chaohua', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('publish_time', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('from_dev', sa.String(length=1024), nullable=True),
    sa.Column('at_names', sa.JSON(), nullable=True),
    sa.Column('forward_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('user_homepage', sa.String(length=1024), nullable=True),
    sa.Column('image_list', sa.JSON(), nullable=True),
    sa.Column('video_list', sa.JSON(), nullable=True),
    sa.Column('topic_list', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wb_user.id'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_weibo')
    # ### end Alembic commands ###
