"""empty message

Revision ID: 7c04714f0dd1
Revises: 
Create Date: 2021-06-07 16:40:19.387684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c04714f0dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('mid', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_avatar', sa.String(length=1024), nullable=True),
    sa.Column('user_name', sa.String(length=256), nullable=True),
    sa.Column('publish_time', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('from_dev', sa.String(length=1024), nullable=True),
    sa.Column('at_names', sa.JSON(), nullable=True),
    sa.Column('forward_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('user_homepage', sa.String(length=1024), nullable=True),
    sa.Column('image_list', sa.JSON(), nullable=True),
    sa.Column('video_list', sa.JSON(), nullable=True),
    sa.Column('topic_list', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('hot', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('feed_id', sa.String(length=32), nullable=True),
    sa.Column('user_avatar', sa.String(length=1024), nullable=True),
    sa.Column('user_name', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.mid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rs_topic_feed',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('feed_mid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['feed_mid'], ['feed.mid'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'feed_mid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rs_topic_feed')
    op.drop_table('comment')
    op.drop_table('topic')
    op.drop_table('feed')
    # ### end Alembic commands ###
