"""empty message

Revision ID: 957b46172b03
Revises: da928f503112
Create Date: 2022-04-19 14:47:09.348308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957b46172b03'
down_revision = 'da928f503112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wb_comment', 'wb_user', ['user_id'], ['id'])
    op.add_column('wb_weibo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wb_weibo', 'wb_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wb_weibo', type_='foreignkey')
    op.drop_column('wb_weibo', 'user_id')
    op.drop_constraint(None, 'wb_comment', type_='foreignkey')
    op.drop_column('wb_comment', 'user_id')
    # ### end Alembic commands ###
