"""empty message

Revision ID: 98ede3e1871a
Revises: fc6cc545091e
Create Date: 2021-06-05 21:47:13.977176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ede3e1871a'
down_revision = 'fc6cc545091e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('link', sa.String(length=1024), nullable=True))
    op.add_column('feed', sa.Column('from_dev', sa.String(length=1024), nullable=True))
    op.add_column('feed', sa.Column('at_names', sa.JSON(), nullable=True))
    op.add_column('feed', sa.Column('user_homepage', sa.String(length=1024), nullable=True))
    op.add_column('feed', sa.Column('topic_list', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'topic_list')
    op.drop_column('feed', 'user_homepage')
    op.drop_column('feed', 'at_names')
    op.drop_column('feed', 'from_dev')
    op.drop_column('feed', 'link')
    # ### end Alembic commands ###
