"""empty message

Revision ID: b8bd96289518
Revises: 957b46172b03
Create Date: 2022-04-20 18:58:21.328908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bd96289518'
down_revision = '957b46172b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_weibo', sa.Column('from_chaohua', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wb_weibo', 'from_chaohua')
    # ### end Alembic commands ###
