"""empty message

Revision ID: cc1213b276eb
Revises: 
Create Date: 2022-04-22 00:33:55.501224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc1213b276eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_text',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('response_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wb_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('avatar', sa.String(length=1024), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wb_weibo',
    sa.Column('mid', sa.String(length=32), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.Column('from_chaohua', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('publish_time', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('from_dev', sa.String(length=1024), nullable=True),
    sa.Column('at_names', sa.JSON(), nullable=True),
    sa.Column('forward_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('user_homepage', sa.String(length=1024), nullable=True),
    sa.Column('image_list', sa.JSON(), nullable=True),
    sa.Column('video_list', sa.JSON(), nullable=True),
    sa.Column('topic_list', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wb_user.id'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_weibo')
    op.drop_table('wb_user')
    op.drop_table('wb_text')
    # ### end Alembic commands ###
