"""empty message

Revision ID: da928f503112
Revises: 
Create Date: 2022-04-17 16:30:10.510771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da928f503112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wb_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('hot', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('avatar', sa.String(length=1024), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wb_weibo',
    sa.Column('mid', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('publish_time', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('from_dev', sa.String(length=1024), nullable=True),
    sa.Column('at_names', sa.JSON(), nullable=True),
    sa.Column('forward_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('user_homepage', sa.String(length=1024), nullable=True),
    sa.Column('image_list', sa.JSON(), nullable=True),
    sa.Column('video_list', sa.JSON(), nullable=True),
    sa.Column('topic_list', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('rs_topic_weibo',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('weibo_mid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['wb_topic.id'], ),
    sa.ForeignKeyConstraint(['weibo_mid'], ['wb_weibo.mid'], ),
    sa.PrimaryKeyConstraint('topic_id', 'weibo_mid')
    )
    op.create_table('wb_comment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('weibo_id', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weibo_id'], ['wb_weibo.mid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_comment')
    op.drop_table('rs_topic_weibo')
    op.drop_table('wb_weibo')
    op.drop_table('wb_user')
    op.drop_table('wb_topic')
    op.drop_table('wb_text')
    # ### end Alembic commands ###
