"""empty message

Revision ID: dd177dc9c073
Revises: b8bd96289518
Create Date: 2022-04-21 22:19:57.827089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd177dc9c073'
down_revision = 'b8bd96289518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_comment')
    op.drop_table('rs_topic_weibo')
    op.drop_index('name', table_name='wb_topic')
    op.drop_table('wb_topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_topic',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('hot', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'wb_topic', ['name'], unique=False)
    op.create_table('rs_topic_weibo',
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weibo_mid', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['wb_topic.id'], name='rs_topic_weibo_ibfk_1'),
    sa.ForeignKeyConstraint(['weibo_mid'], ['wb_weibo.mid'], name='rs_topic_weibo_ibfk_2'),
    sa.PrimaryKeyConstraint('topic_id', 'weibo_mid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wb_comment',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('weibo_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('like_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reply_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wb_user.id'], name='wb_comment_ibfk_2'),
    sa.ForeignKeyConstraint(['weibo_id'], ['wb_weibo.mid'], name='wb_comment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
